name: 'clj-holmes (Clojure)'
author: 'clj-holmes'
description: 'Executes clj-holmes security scan in clojure/clojurescript projects.'
inputs:
  rules-repository:
    description: 'repository containing all the rules'
    required: false
    default: 'git://clj-holmes/clj-holmes-rules#main'
  output-type:
    description: 'Output type'
    required: false
    default: 'sarif'
  output-file:
    description: 'Output file'
    required: false
    default: 'clj_holmes_scan_results.txt'
  fail-on-result:
    description: 'Enable or disable fail if results were found'
    required: false
    default: 'false'
  no-verbose:
    description: 'Enable or disable progress bar'
    required: false
    default: 'true'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.rules-repository }}
    - ${{ inputs.output-type }}
    - ${{ inputs.output-file }}
    - ${{ inputs.fail-on-result }}
    - ${{ inputs.no-verbose }}

branding:
 color: gray-dark
 icon: shield
